name: SignCommands
main: com.celeo.signcommands.SignCommands
author: Celeo
version: 1.0
description: Plugin that players to buy land
commands:
  sc:
    description: Plugin-specific commands for server admins
    usage: /<command> [parameters]